name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Prepare Google Application Credentials
      shell: bash
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" | base64 --decode > "google-application-credentials.json"

    - name: Deploy to Firebase Hosting
      run: |
        firebase deploy --non-interactive --debug

    - name: Remove credentials file
        if: success() || failure()
        run: |
          rm google-application-credentials.json
